### ISSUE TITLE
Missing Script Log Spam

### ISSUE THREAD

**Issue by Matt-662607015** [Piggy3590/LC_Office#17]
With only LC_Office, InputUtils, dependencies, and default config options, the console and log are spammed with problems about missing scripts.

Steps to Reproduce:
1. Install LC_Office.
2. Open the game.

[LogOutput.log](https://github.com/Piggy3590/LC_Office/files/14499304/LogOutput.log)

**Comment by Valafi** [comment]
This is not solved, by the way. On the latest version with only LC_Office installed the log is spammed with warnings.

![missing_script_spam](https://github.com/Piggy3590/LC_Office/assets/16008982/dde45974-5695-48d1-82d5-d59298b7a53e)

**Comment by Piggy3590** [comment]
Although it has been known since 0.0.3, the cause has not yet been found and it does not seem to be a very important bug.
