### ISSUE TITLE
LoaforcAPI/LethalResonance incompatability?

### ISSUE THREAD

**Issue by Catpyre** [Piggy3590/LC_Office#21]
Whenever loaforcs soundapi is loaded there is a bunch of missing referenced script errors that pop up during LC_Office's generation in the logs when its starting up/loading. I reported this to Loaforc's github and it seems like its mostly an issue with how LCOffice is loading audio? (And as a side note it seems the networking this mod uses might cause conflicts elsewhere with other mods? Hard to tell exactly but there's been a few cases of desync that gets fixed if this mod and its dependancies get disabled primarily with loading in new players on the ship)

> [Info :me.loaforc.soundapi] Loaded LethalResonance(non-startup) in 11387ms.
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'EntranceTeleportB') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'VentEntrance') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'IndirectLight') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh (1)') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Boombox') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'EntranceTeleportA') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'BigDoor') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'SteelDoorMapModel') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'LungApparatusTurnedOff') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'CollisionMesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object '') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'mesh') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Cube (1)') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'TurretContainer') is missing!
> [Warning: Unity Log] The referenced script on this Behaviour (Game Object 'Light') is missing!

**Comment by Piggy3590** [comment]
thats a general warning, you can ignore it (occurs even without LethalResonance mod).
problems with LethalNetworkAPI should probably be reported in LNAPI's repo or thread, not here
