### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by CatsArmy** [Piggy3590/LC_Office#3]
I know this is the wrong mod buttt LastRunResults is or private or not on github and it was pretty hard to find this btw
Mod: LastRunResults
so my suggestion is to have the option for it to not show up when in terminal

**Comment by Piggy3590** [comment]
ok later
I don't know why I set the github link to dis lmao

**Comment by CatsArmy** [comment]
btw maybe you should also save the last run somewhere for each save file as it gets reset i belive

**Comment by CatsArmy** [comment]
???

**Comment by CatsArmy** [comment]
heya its been a while just thought id ask if this is a planed feature

**Comment by Piggy3590** [comment]
i just updated ;))

> heya its been a while just thought id ask if this is a planed feature
