### ISSUE TITLE
Cant play v55 

### ISSUE THREAD

**Issue by RezMeRainzy** [Piggy3590/LC_Office#30]
With this mod installed, v55 is impossible to play. You get stuck in some blank atmosphere with the cursor on your screen unable to do anything

**Comment by Skyblade799** [comment]
Can't play the release version of V56 (no longer in beta). Mysteriously spawns in two dysfunctional "players" inside of the ship, and prevents climbing ladders anywhere. Haven't checked the rest of the interior, but I'd safely assume it's now broken with the update. Will need wait for a patch.
