### ISSUE TITLE
Elevator desync

### ISSUE THREAD

**Issue by MightyBunch** [Piggy3590/LC_Office#4]
It seems there is some kind of desynchronization between certain players. Let's start with the fact that from the first person, entering the elevator looks normal, but from the side, it seems like the person first flies up through the textures and then appears in the elevator. But this is not a big problem; you can get used to it. 
However, for some reason, sometimes when one person enters the elevator, it's like they're entering another dimension. They appear in their own elevator, unable to see or hear other players, and other players cannot see or hear them. They can go up and down the elevator, but for everyone else, the elevator appears stationary. Then, that person just appears out of nowhere on another floor. For that person, when another players take the elevator, it looks the same - they disappear and appear on another floor. I hope you understand what I just said)

**Comment by Piggy3590** [comment]
I'm not sure cuz I've never seen before. do you have any video?

**Comment by MightyBunch** [comment]
Upload a video to google drive, qithub can't upload any video 10MB+
https://drive.google.com/file/d/10x3QN-TXOCPOfCOjKUW_wtc6lX6MEtY0/view?usp=sharing
So it's from my perspective and as you see my friend enters an elevator and just flies to ground, but from his perspective as he told me he was in elevator and he could not see my other friend.
Another video when i was alive:
https://drive.google.com/file/d/1ZHfv7vQ8CsIhi8Pu6HNZF5d6NbLifJEm/view?usp=sharing
As you see he is just disappears. One minute later he showed up and told me that he was in the elevator but we disappear, and he was using it to go up and down at the same time as we are. Hope that helps.

**Comment by Piggy3590** [comment]
Are you using ShipLobby or LateCompany mod?

**Comment by MightyBunch** [comment]
No, we know about desync problems with this mod thats why we are not using it)

**Comment by MightyBunch** [comment]
We can test it without any other mods if you think it can be a cause of it.

**Comment by MightyBunch** [comment]
Have tested it with friend. No other mods than LC office and dependencies. That what i have find out:
This issue is happening at 50% chance when landing on the moon, so if you landed and it's broken, then it will be broken for all round until going to the orbit.

So, normal behavior is looking like this:
https://drive.google.com/file/d/1KW0MFnsqaDtJRCPe7tSBEt3DHdEDc-UD/view?usp=sharing
When entering an elevator there is some visual bug, when player jump throug textures, but it is nothing bad. It would be great if it was not like that, but it is what it is.

Then, the wrong behavior looks like this:
https://drive.google.com/file/d/1YwgObzPOZi8_k0sB6xkgxq4CNrvPQK5N/view?usp=sharing
When entering the elevator player is disappearing, i can't see or hear him. But, actually, i was wrong in prevoius messages when said that player in elevator can't hear and see player outside - he actually see and hear everything as usual, and only when player outside entering an elevator he disappears for player in elevator too.

And then, another one footage on this problem:
https://drive.google.com/file/d/1BvyDIa2VvwE6M4HeXpmczJ3X57pUbD8M/view?usp=sharing
As you can see, when that problem appears, player in elevator can travel up and down in it when for other players elevator is standing on one place. And then when he leaves the elevator on another floor, for other players he just appears out of nowhere. Also, as you can see, there is snow footsteps appearing when player appears. It is because it's a Titan, and player do not totally disappears in elevator, he is actually being teleported to somewhere next to the ship (previously saw it when died and spectating my another friend). I think it's just a 0.0 coordinates or something, and game just can't understand the position of player.

And, also, there is a console error that appears if i am entering or leaving elevator, and it appears in my friend's console when he is entering or leaving the elevator:
____________________________________________________________________________________________
[Error  :LethalNetworkAPI] Unable to invoke the Piggy.LCOffice.msg.SendInElevator with identifier "message". Is the player in a lobby?
____________________________________________________________________________________________
So that is all that i found. Hope that helps.

**Comment by MightyBunch** [comment]
Aaaaaaand that was a LethalNetworkAPI bug that was fixed in the last update 4 days ago. Sorry for bothering with this one :/

**Comment by Piggy3590** [comment]
good to know, I was figuring out the cause lmao👍
