### ISSUE TITLE
Shrimp isn't spawning

### ISSUE THREAD

**Issue by MightyBunch** [Piggy3590/LC_Office#5]
So shrimp is not spawning. Maybe he is very rare or something, but it looks like he did not even present in enemy spawn choose on any moon(or how i can discribe this):
_____________________________________________________________________________________________________
[Info   : Unity Log] spawn chance range min/max : -5, 2; time of day percent: 0,09259259
[Info   : Unity Log] spawn chance range min/max (non integer) : -5,268714, 2,731286
[Info   : Unity Log] base chance daytime: -8,873613
[Info   : Unity Log] timeuptocurrenthour: 120; totalTime: 1080
[Info   : Unity Log] AnomalyRandom 2: 0
[Info   : Unity Log] spawn chance range min/max : -5, 2; time of day percent: 0,09261537
[Info   : Unity Log] spawn chance range min/max (non integer) : -5,26822, 2,73178
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Centipede
[Info   : Unity Log] enemy №0 probability - 27
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Bunker Spider
[Info   : Unity Log] enemy №1 probability - 44
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Hoarding bug
[Info   : Unity Log] enemy №2 probability - 16
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Flowerman
[Info   : Unity Log] enemy №3 probability - 3
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Crawler
[Info   : Unity Log] enemy №4 probability - 53
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Blob
[Info   : Unity Log] enemy №5 probability - 31
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Spring
[Info   : Unity Log] enemy №6 probability - 25
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Puffer
[Info   : Unity Log] enemy №7 probability - 7
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Nutcracker
[Info   : Unity Log] enemy №8 probability - 2
[Info   : Unity Log] ADDING ENEMY №4: Crawler
[Info   : Unity Log] Adding 3 to power level, enemy: Crawler
_____________________________________________________________________________________________________
It is from my output file. As you see, shrimp isn't there. The only moon where shrimp can spawn as i tested is Experimentation. That is a log from that moon:
_____________________________________________________________________________________________________
[Info   : Unity Log] spawn chance range min/max : -5, 2; time of day percent: 0,09259259
[Info   : Unity Log] spawn chance range min/max (non integer) : -5,64065, 2,35935
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Centipede
[Info   : Unity Log] enemy №0 probability - 51
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Bunker Spider
[Info   : Unity Log] enemy №1 probability - 58
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Hoarding bug
[Info   : Unity Log] enemy №2 probability - 28
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Flowerman
[Info   : Unity Log] enemy №3 probability - 13
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Crawler
[Info   : Unity Log] enemy №4 probability - 15
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Blob
[Info   : Unity Log] enemy №5 probability - 30
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Girl
[Info   : Unity Log] enemy №6 probability - 0
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Puffer
[Info   : Unity Log] enemy №7 probability - 28
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Nutcracker
[Info   : Unity Log] enemy №8 probability - 1
[Info   : Unity Log] Setting enemy numberspawned to 0 to start: Shrimp                              <----------There he is
[Info   : Unity Log] enemy №9 probability - 2
[Info   : Unity Log] ADDING ENEMY №0: Centipede
[Info   : Unity Log] Adding 1 to power level, enemy: Centipede
_____________________________________________________________________________________________________
But as you see here:
_____________________________________________________________________________________________________
[Info   :Piggy.LCOffice] Shrimp spawn chance in ExperimentationLevel: 2
[Info   :Piggy.LCOffice] Shrimp spawn chance in AssuranceLevel: 4
[Info   :Piggy.LCOffice] Shrimp spawn chance in VowLevel: 5
[Info   :Piggy.LCOffice] Shrimp spawn chance in MarchLevel: 8
[Info   :Piggy.LCOffice] Shrimp spawn chance in OffenseLevel: 6
[Info   :Piggy.LCOffice] Shrimp spawn chance in RendLevel: 16
[Info   :Piggy.LCOffice] Shrimp spawn chance in DineLevel: 15
[Info   :Piggy.LCOffice] Shrimp spawn chance in TitanLevel: 20
[Info   :Piggy.LCOffice] Shrimp spawn chance in Modded Moons: 18
_____________________________________________________________________________________________________
Config file is working and your mod sees the values in config file.
That's all.

**Comment by Piggy3590** [comment]
I'm not sure -- but it seems normal.

**Comment by MightyBunch** [comment]
I mean, we played like 3 or 4 days with mod with slightly tweaked spawn rates of shrimp, 8-9 quotas in day, and we never saw shrimp. I just wanted to see may it be that he can't spawn and that what i found in log file - when game chooses who can spawn, there is no shrimp in that choosing, only on experimentatikn he in. When using other mods that add enemies to the game that enemies is in that choosing. So, what do you think?

**Comment by MightyBunch** [comment]
As expected, if you download mod that provides with ability to modify default enemy weight on every moon, the default weight of shrimp spawn is 0 on every map except Experimentation - on Experimentation default value is a value from lcoffice config. No other mods installed when tested.

**Comment by dopadream** [comment]
Can confirm, shrimps spawning is completely broken and his weight will be 0 regardless of config setting
