### ISSUE TITLE
Issue with shadows

### ISSUE THREAD

**Issue by MightyBunch** [Piggy3590/LC_Office#6]
I hope I'm not boring you.

So, there is an issue, that is happening when looking in some directions. No other mods.
https://drive.google.com/file/d/1rtDDwyu7FPTQH8IuWIIPuqGmLwKbUtJH/view?usp=sharing
It maybe not like huge, but it can look worse. Fps dropping, all the shadows flickering.

There is also log warning that spamming in console when that is happening:
______________________________________________________________________________________________
[Warning: Unity Log] Max shadow requests count reached, dropping all exceeding requests. You can increase this limit by changing the Maximum Shadows on Screen property in the HDRP asset.
______________________________________________________________________________________________

**Comment by Piggy3590** [comment]
I think I need to edit the room a bit

**Comment by Piggy3590** [comment]
Its been a while since it was fixed lol
I forgot and didnt close it
