### ISSUE TITLE
Networking for the lung/elevator is still broken and does not behave properly

### ISSUE THREAD

**Issue by dopadream** [Piggy3590/LC_Office#8]
Starting a run on a map that has the Office interior prints this upon loading the level;

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCOffice.Patches.ElevatorSystem.Start () (at <ea9ba628958442858a11a8208a1267ae>:IL_0019)

At first glance, this isn't an issue, but if you take the apparatus out things quickly start to go wrong.
Taking out the apparatus will not cause the elevator to think it turned off, and does not properly power the elevator. I can't exactly tell what the server is successfully sending to the client and vice versa, but I have noticed some pretty nasty results including getting softlocked in the elevator, desyncs in multiplayer, the elevator starting without power even if the facility has power, etc. 
Here's a video showing some of these issues:
https://www.youtube.com/watch?v=EWl60xfvNew

Also, when taking the apparatus out, upon ending the day (going back into orbit) and going back to the office again, the elevator will immediately start in a half powered on/off state with no way to control it. It also spams the console with this error when this happens:
![image](https://github.com/Piggy3590/LC_Office/assets/68942129/23d8559c-505c-4919-9fed-f0080eb8fb0e)

**Comment by dopadream** [comment]
Currently looking into this on my own local build of this, will keep posted if I find any workarounds

**Comment by dopadream** [comment]
Wait you fixed it? Does it not desync anymore?

**Comment by Piggy3590** [comment]
I removed lung system and no desync issues reported since 1.0.4
